# cargo-features = ["strip"]

[package]
name = "red"
version = "0.1.0"
edition = "2018"

[dependencies]
nom = "7"
regex = {version="1.5", default-features=false, features=["std", "perf-cache", "perf-dfa", "perf-inline"]}

# [profile.release]
# strip = "symbols"
